# backend/app/ai/shared/__init__.py
# ─────────────────────────────────────────────────────────────────────────────
# Shared Module
# Shared response models, exceptions, constants, and types
# ─────────────────────────────────────────────────────────────────────────────

from app.ai.shared.responses import (
    AIResponse,
    ChatResponse,
    VisionResponse,
    DiagnosisResponse,
    PrescriptionResponse,
    LabResponse,
    ReportResponse,
)
from app.ai.shared.exceptions import (
    AIBaseException,
    ProviderError,
    ModelNotFoundError,
    PromptError,
    WorkflowError,
    RetrievalError,
    MemoryError,
    VisionError,
    ClinicalError,
    ConfigurationError,
    ValidationError,
)
from app.ai.shared.constants import (
    PROVIDER_GROQ,
    PROVIDER_OPENAI,
    PROVIDER_ANTHROPIC,
    PROVIDER_HUGGINGFACE,
    TASK_CHAT,
    TASK_REASONING,
    TASK_VISION,
    TASK_REWRITE,
    TASK_OCR,
    TASK_EMBEDDING,
    WORKFLOW_CHAT,
    WORKFLOW_VISION,
    WORKFLOW_DIAGNOSIS,
    WORKFLOW_PRESCRIPTION,
    WORKFLOW_LAB,
    WORKFLOW_REPORT,
    CONFIDENCE_HIGH,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_LOW,
    EXECUTION_TIME_WARNING,
    EXECUTION_TIME_CRITICAL,
    CONVERSATION_MEMORY_LIMIT,
    SUMMARY_MEMORY_LIMIT,
    DEFAULT_RETRIEVAL_K,
    DEFAULT_RETRIEVAL_FETCH_K,
    CONTEXT_LENGTH_SHORT,
    CONTEXT_LENGTH_MEDIUM,
    CONTEXT_LENGTH_LONG,
    CONTEXT_LENGTH_VERY_LONG,
    TEMPERATURE_PRECISE,
    TEMPERATURE_BALANCED,
    TEMPERATURE_CREATIVE,
)
from app.ai.shared.types import (
    Provider,
    TaskType,
    WorkflowType,
    Message,
    Citation,
    RetrievedDocument,
)

__all__ = [
    # Responses
    "AIResponse",
    "ChatResponse",
    "VisionResponse",
    "DiagnosisResponse",
    "PrescriptionResponse",
    "LabResponse",
    "ReportResponse",
    # Exceptions
    "AIBaseException",
    "ProviderError",
    "ModelNotFoundError",
    "PromptError",
    "WorkflowError",
    "RetrievalError",
    "MemoryError",
    "VisionError",
    "ClinicalError",
    "ConfigurationError",
    "ValidationError",
    # Constants
    "PROVIDER_GROQ",
    "PROVIDER_OPENAI",
    "PROVIDER_ANTHROPIC",
    "PROVIDER_HUGGINGFACE",
    "TASK_CHAT",
    "TASK_REASONING",
    "TASK_VISION",
    "TASK_REWRITE",
    "TASK_OCR",
    "TASK_EMBEDDING",
    "WORKFLOW_CHAT",
    "WORKFLOW_VISION",
    "WORKFLOW_DIAGNOSIS",
    "WORKFLOW_PRESCRIPTION",
    "WORKFLOW_LAB",
    "WORKFLOW_REPORT",
    "CONFIDENCE_HIGH",
    "CONFIDENCE_MEDIUM",
    "CONFIDENCE_LOW",
    "EXECUTION_TIME_WARNING",
    "EXECUTION_TIME_CRITICAL",
    "CONVERSATION_MEMORY_LIMIT",
    "SUMMARY_MEMORY_LIMIT",
    "DEFAULT_RETRIEVAL_K",
    "DEFAULT_RETRIEVAL_FETCH_K",
    "CONTEXT_LENGTH_SHORT",
    "CONTEXT_LENGTH_MEDIUM",
    "CONTEXT_LENGTH_LONG",
    "CONTEXT_LENGTH_VERY_LONG",
    "TEMPERATURE_PRECISE",
    "TEMPERATURE_BALANCED",
    "TEMPERATURE_CREATIVE",
    # Types
    "Provider",
    "TaskType",
    "WorkflowType",
    "Message",
    "Citation",
    "RetrievedDocument",
]
