"""
medical_disclaimer.py
=====================
Medical disclaimer injection for the MedCortex AI Safety subsystem.

Provides standardised, configurable disclaimer text that can be appended to
AI-generated medical responses to comply with healthcare communication
regulations and best practices.
"""

from __future__ import annotations

import re

from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class DisclaimerConfig(BaseModel):
    """Configuration for which disclaimer sections to include.

    Attributes:
        include_general: Append the general medical information disclaimer.
        include_emergency: Append emergency contact guidance when relevant.
        include_professional: Append advice to seek professional consultation.
    """

    include_general: bool = True
    include_emergency: bool = True
    include_professional: bool = True


# ---------------------------------------------------------------------------
# Disclaimer constants
# ---------------------------------------------------------------------------

GENERAL_DISCLAIMER: str = (
    "⚕️ **Medical Information Disclaimer**: The information provided in this "
    "response is for general educational and informational purposes only. It "
    "does not constitute medical advice, diagnosis, or treatment. MedCortex AI "
    "responses are generated by an AI system and may not reflect the most "
    "current medical guidelines or your individual health circumstances."
)

EMERGENCY_DISCLAIMER: str = (
    "🚨 **Emergency Notice**: If you or someone else is experiencing a medical "
    "emergency, please call emergency services immediately (e.g., 911 in the "
    "US, 999 in the UK, 112 in the EU, or your local emergency number). Do not "
    "rely on AI-generated information in life-threatening situations."
)

PROFESSIONAL_DISCLAIMER: str = (
    "👨‍⚕️ **Professional Consultation**: Always consult a qualified and licensed "
    "healthcare professional before making any medical decisions, starting or "
    "stopping any treatment, or acting on any health information. Individual "
    "medical situations vary greatly and require personalised assessment."
)

# ---------------------------------------------------------------------------
# Emergency keyword detection
# ---------------------------------------------------------------------------

_EMERGENCY_KEYWORDS: list[str] = [
    "chest pain", "heart attack", "stroke", "difficulty breathing",
    "shortness of breath", "unconscious", "seizure", "severe bleeding",
    "anaphylaxis", "allergic reaction", "overdose", "poisoning",
    "suicidal", "suicide", "self-harm", "emergency", "call 911",
    "call 999", "call 112", "ambulance", "life-threatening",
    "severe chest", "cannot breathe", "can't breathe",
    "severe abdominal pain", "sudden numbness", "sudden confusion",
    "sudden severe headache",
]

_EMERGENCY_RE = re.compile(
    r"\b(?:" + "|".join(re.escape(kw) for kw in _EMERGENCY_KEYWORDS) + r")\b",
    re.IGNORECASE,
)

# Separator used between response and disclaimers.
_SECTION_SEPARATOR = "\n\n---\n\n"
_BLOCK_SEPARATOR = "\n\n"


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------


class MedicalDisclaimer:
    """Inject standardised medical disclaimers into AI response text.

    Disclaimer sections are appended (never prepended) to preserve the natural
    flow of the informational content.  The :meth:`needs_emergency_disclaimer`
    method can be used independently for routing logic upstream of injection.

    Usage::

        disclaimer = MedicalDisclaimer()
        config = DisclaimerConfig(include_emergency=False)
        safe_response = disclaimer.inject(response_text, config)
    """

    #: Re-exported constants for external access without needing to import globals.
    GENERAL_DISCLAIMER: str = GENERAL_DISCLAIMER
    EMERGENCY_DISCLAIMER: str = EMERGENCY_DISCLAIMER
    PROFESSIONAL_DISCLAIMER: str = PROFESSIONAL_DISCLAIMER

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def inject(self, response: str, config: DisclaimerConfig) -> str:
        """Append appropriate disclaimer sections to *response*.

        The emergency disclaimer is only injected when
        :meth:`needs_emergency_disclaimer` returns ``True`` *and*
        ``config.include_emergency`` is ``True``.

        Args:
            response: The AI-generated response text to be augmented.
            config: Controls which disclaimer sections are included.

        Returns:
            The original response followed by all applicable disclaimers,
            separated by a horizontal rule.
        """
        parts: list[str] = [response.rstrip()]
        disclaimer_blocks: list[str] = []

        if config.include_general:
            disclaimer_blocks.append(GENERAL_DISCLAIMER)

        if config.include_emergency and self.needs_emergency_disclaimer(response):
            disclaimer_blocks.append(EMERGENCY_DISCLAIMER)

        if config.include_professional:
            disclaimer_blocks.append(PROFESSIONAL_DISCLAIMER)

        if disclaimer_blocks:
            parts.append(_SECTION_SEPARATOR + _BLOCK_SEPARATOR.join(disclaimer_blocks))

        return "".join(parts)

    def needs_emergency_disclaimer(self, response: str) -> bool:
        """Determine whether the response content warrants an emergency disclaimer.

        Args:
            response: The AI-generated response text to inspect.

        Returns:
            ``True`` if the response contains keywords associated with
            medical emergencies; ``False`` otherwise.
        """
        return bool(_EMERGENCY_RE.search(response))
